// This file serves the OpenAPI 3.1 spec (FR-API-003) and a Swagger UI page. The
// spec is generated by swaggo/swag v2 (`swag init … --v3.1`) into docs/ and copied
// here for embedding; regenerate via `make openapi` (see the Makefile target). The
// JSON is served publicly; the interactive UI is mounted non-prod only.
package handlers

import (
	_ "embed"
	"net/http"
)

//go:embed openapi.json
var openapiSpec []byte

// OpenAPIHandlers serves the API spec + docs UI.
type OpenAPIHandlers struct{}

// NewOpenAPIHandlers builds the handler set.
func NewOpenAPIHandlers() *OpenAPIHandlers { return &OpenAPIHandlers{} }

// Spec: GET /api/v1/openapi.json — the generated OpenAPI 3.1 document.
func (h *OpenAPIHandlers) Spec(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", "no-cache")
	_, _ = w.Write(openapiSpec)
}

// swaggerUIPage is a minimal Swagger UI shell that loads the spec from the sibling
// endpoint. Served only in non-prod (wired in the router).
const swaggerUIPage = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>Fluxboard API — Docs</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css"/>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script>
    window.ui = SwaggerUIBundle({ url: '/api/v1/openapi.json', dom_id: '#swagger-ui' });
  </script>
</body>
</html>`

// Docs: GET /api/docs — interactive Swagger UI (non-prod only).
func (h *OpenAPIHandlers) Docs(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = w.Write([]byte(swaggerUIPage))
}
